version: '3'
services:
    api:
        ports:
            - '5000:5000'
    
    web:
        build:
            args:
                - API_URL=http://localhost:5000/
        ports:
            - '80:80'